# Generated by Django 2.2.3 on 2020-05-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='childeren',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seats',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='smoking',
            field=models.BooleanField(null=True),
        ),
    ]
